# Your translations go here. To be used with the 'translate' liquid filter
# Example:
#   {{ 'hello_world' | translate }}
#

# hello_world:
#   en: Hello world !
#   fr: Bonjour le monde !
home_page:
  en: Home 
  ja: Beranda

read_more:
  en: Read More
  ja: もっと見る

en:
  ja: English

ja:
  en: Jepang

posted_at_format:
  en: 'Posted at %-I:%M %p on %B, %-d %Y'
  ja: '%Y年%-m月%-d日 %H:%M'